name: Firebase Deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploy to Staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'  # Ejecutar solo si es la rama staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Enable webframeworks
      run: firebase experiments:enable webframeworks

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase Staging
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }}

  deploy_production:
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ejecutar solo si es la rama main

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Enable webframeworks
      run: firebase experiments:enable webframeworks

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase Production
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }}